id = "clojure"
name = "Clojure"
description = "Clojure support."
version = "0.1.0"
schema_version = 1
authors = ["Paulo Roberto de Oliveira Castro <p.oliveira.castro@gmail.com>"]
repository = "https://github.com/zed-extensions/clojure"

[language_servers.clojure-lsp]
name = "clojure-lsp"
language = "Clojure"

[grammars.clojure]
repository = "https://github.com/prcastro/tree-sitter-clojure"
commit = "38b4f8d264248b2fd09575fbce66f7c22e8929d5"
