name = "Clojure"
grammar = "clojure"
path_suffixes = ["clj", "cljs", "cljc", "cljd", "edn", "bb"]
line_comments = [";; "]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
# See https://clojure.org/reference/reader#_reader_forms
word_characters = ["*", "+", "!", "-", "_", "'", "?", "<", ">", "="]
tab_size = 2
